# Cloudflare Worker Configuration
name = "onetip"
main = "src/index.js"
compatibility_date = "2024-10-06"

[assets]
directory = "."
binding = "ASSETS"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "onetip"
database_id = "c4e7f8d5-c6c3-4b62-855d-02d531dee71a"
